### ISSUE TITLE
Merge DependencyInjection packages with their implementation packages

### ISSUE THREAD

**Issue by TheName** [TheName/EventSourcing#24]
Having so many projects (and NuGet packages) is hard to maintain, work with (IDE is slow at least partially due to the amount of projects within solution) and most likely will be confusing for users.

Initially I wanted to limit dependencies in every package, that's why I even split DependencyInjection configuration into a separate package. Due to that there's no dependency on package like `Microsoft.Extensions.Options.ConfigurationExtensions` in the implementation packages...
But then again, implementation packages rely heavily on internal classes (to make it easy to introduce changes in the future), so using these implementations without Microsoft's DependencyInjection becomes almost impossible anyway...

So the trade-off is not worth it. Let's make these dependencies explicit and limit the amount of projects.

Packages/projects to merge:

- [x] `Extensions.DependencyInjection` => `EventSourcing`
- [x] `Extensions.DependencyInjection.Aggregates` => `Aggregates`
- [x] `Extensions.DependencyInjection.Bus` => `Bus`
- [x] `Extensions.DependencyInjection.Bus.RabbitMQ` => `Bus.RabbitMQ`
- [x] `ForgettablePayloads.DependencyInjection.Persistence` => `ForgettablePayloads.Persistence`
- [x] `Extensions.DependencyInjection.PostgreSql` => `ForgettablePayloads.Persistence.PostgreSql`
- [x] `Extensions.DependencyInjection.SqlServer` => `ForgettablePayloads.Persistence.SqlServer`
- [x] `ForgettablePayloads.Extensions.DependencyInjection` => `ForgettablePayloads`
- [x] `Extensions.DependencyInjection.Persistence.PostgreSql` => `Persistence.PostgreSql`
- [x] `Extensions.DependencyInjection.Persistence.SqlServer` => `Persistence.SqlServer`
- [x] `Extensions.DependencyInjection.Persistence` => `Persistence`  :: done in #37 
- [x] `Extensions.DependencyInjection.Serialization` => `Serialization` :: done in #38
- [x] `Extensions.DependencyInjection.Serialization.Json` => `Serialization.Json` :: done in #39
- [x] `Extensions.DependencyInjection.Serialization.NewtonsoftJson` => `Serialization.NewtonsoftJson` :: done in #40

**Comment by TheName** [comment]
related #31
